# Travis Build Configure

# Build
language: php
php:
  - 7.2
install: composer install
script: php build.php
# Deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: gh-pages
